CAYLEY_TABLE = {
    ('I', 'I'): 'I', ('I', 'H'): 'H', ('I', 'S'): 'S', ('I', 'SH'): 'SH', ('I', 'HS'): 'HS', ('I', 'SS'): 'SS', ('I', 'HSH'): 'HSH', ('I', 'SSH'): 'SSH', ('I', 'SHS'): 'SHS', ('I', 'HSS'): 'HSS', ('I', 'SSS'): 'SSS', ('I', 'SHSH'): 'SHSH', ('I', 'HSSH'): 'HSSH', ('I', 'SSSH'): 'SSSH', ('I', 'SSHS'): 'SSHS', ('I', 'SHSS'): 'SHSS', ('I', 'SSHSH'): 'SSHSH', ('I', 'SHSSH'): 'SHSSH', ('I', 'HSSHS'): 'HSSHS', ('I', 'SSSHS'): 'SSSHS', ('I', 'SSHSS'): 'SSHSS', ('I', 'HSSHSH'): 'HSSHSH', ('I', 'SSSHSH'): 'SSSHSH', ('I', 'SSHSSH'): 'SSHSSH',
    
    ('H', 'I'): 'H', ('H', 'H'): 'I', ('H', 'S'): 'HS', ('H', 'SH'): 'HSH', ('H', 'HS'): 'S', ('H', 'SS'): 'HSS', ('H', 'HSH'): 'SH', ('H', 'SSH'): 'HSSH', ('H', 'SHS'): 'SSSH', ('H', 'HSS'): 'SS', ('H', 'SSS'): 'SHSH', ('H', 'SHSH'): 'SSS', ('H', 'HSSH'): 'SSH', ('H', 'SSSH'): 'SHS', ('H', 'SSHS'): 'HSSHS', ('H', 'SHSS'): 'SSSHS', ('H', 'SSHSH'): 'HSSHSH', ('H', 'SHSSH'): 'SSSHSH', ('H', 'HSSHS'): 'SSHS', ('H', 'SSSHS'): 'SHSS', ('H', 'SSHSS'): 'SSHSSH', ('H', 'HSSHSH'): 'SSHSH', ('H', 'SSSHSH'): 'SHSSH', ('H', 'SSHSSH'): 'SSHSS',
    
    ('S', 'I'): 'S', ('S', 'H'): 'SH', ('S', 'S'): 'SS', ('S', 'SH'): 'SSH', ('S', 'HS'): 'SHS', ('S', 'SS'): 'SSS', ('S', 'HSH'): 'SHSH', ('S', 'SSH'): 'SSSH', ('S', 'SHS'): 'SSHS', ('S', 'HSS'): 'SHSS', ('S', 'SSS'): 'I', ('S', 'SHSH'): 'SSHSH', ('S', 'HSSH'): 'SHSSH', ('S', 'SSSH'): 'H', ('S', 'SSHS'): 'SSSHS', ('S', 'SHSS'): 'SSHSS', ('S', 'SSHSH'): 'SSSHSH', ('S', 'SHSSH'): 'SSHSSH', ('S', 'HSSHS'): 'HSSH', ('S', 'SSSHS'): 'HS', ('S', 'SSHSS'): 'HSSHSH', ('S', 'HSSHSH'): 'HSS', ('S', 'SSSHSH'): 'HSH', ('S', 'SSHSSH'): 'HSSHS',
    
    ('SH', 'I'): 'SH', ('SH', 'H'): 'S', ('SH', 'S'): 'SHS', ('SH', 'SH'): 'SHSH', ('SH', 'HS'): 'SS', ('SH', 'SS'): 'SHSS', ('SH', 'HSH'): 'SSH', ('SH', 'SSH'): 'SHSSH', ('SH', 'SHS'): 'H', ('SH', 'HSS'): 'SSS', ('SH', 'SSS'): 'SSHSH', ('SH', 'SHSH'): 'I', ('SH', 'HSSH'): 'SSSH', ('SH', 'SSSH'): 'SSHS', ('SH', 'SSHS'): 'HSSH', ('SH', 'SHSS'): 'HS', ('SH', 'SSHSH'): 'HSS', ('SH', 'SHSSH'): 'HSH', ('SH', 'HSSHS'): 'SSSHS', ('SH', 'SSSHS'): 'SSHSS', ('SH', 'SSHSS'): 'HSSHS', ('SH', 'HSSHSH'): 'SSSHSH', ('SH', 'SSSHSH'): 'SSHSSH', ('SH', 'SSHSSH'): 'HSSHSH',
    
    ('HS', 'I'): 'HS', ('HS', 'H'): 'HSH', ('HS', 'S'): 'HSS', ('HS', 'SH'): 'HSSH', ('HS', 'HS'): 'SSSH', ('HS', 'SS'): 'SHSH', ('HS', 'HSH'): 'SSS', ('HS', 'SSH'): 'SHS', ('HS', 'SHS'): 'HSSHS', ('HS', 'HSS'): 'SSSHS', ('HS', 'SSS'): 'H', ('HS', 'SHSH'): 'HSSHSH', ('HS', 'HSSH'): 'SSSHSH', ('HS', 'SSSH'): 'I', ('HS', 'SSHS'): 'SHSS', ('HS', 'SHSS'): 'SSHSSH', ('HS', 'SSHSH'): 'SHSSH', ('HS', 'SHSSH'): 'SSHSS', ('HS', 'HSSHS'): 'SSH', ('HS', 'SSSHS'): 'S', ('HS', 'SSHSS'): 'SSHSH', ('HS', 'HSSHSH'): 'SS', ('HS', 'SSSHSH'): 'SH', ('HS', 'SSHSSH'): 'SSHS',
    
    ('SS', 'I'): 'SS', ('SS', 'H'): 'SSH', ('SS', 'S'): 'SSS', ('SS', 'SH'): 'SSSH', ('SS', 'HS'): 'SSHS', ('SS', 'SS'): 'I', ('SS', 'HSH'): 'SSHSH', ('SS', 'SSH'): 'H', ('SS', 'SHS'): 'SSSHS', ('SS', 'HSS'): 'SSHSS', ('SS', 'SSS'): 'S', ('SS', 'SHSH'): 'SSSHSH', ('SS', 'HSSH'): 'SSHSSH', ('SS', 'SSSH'): 'SH', ('SS', 'SSHS'): 'HS', ('SS', 'SHSS'): 'HSSHSH', ('SS', 'SSHSH'): 'HSH', ('SS', 'SHSSH'): 'HSSHS', ('SS', 'HSSHS'): 'SHSSH', ('SS', 'SSSHS'): 'SHS', ('SS', 'SSHSS'): 'HSS', ('SS', 'HSSHSH'): 'SHSS', ('SS', 'SSSHSH'): 'SHSH', ('SS', 'SSHSSH'): 'HSSH',
    
    ('HSH', 'I'): 'HSH', ('HSH', 'H'): 'HS', ('HSH', 'S'): 'SSSH', ('HSH', 'SH'): 'SSS', ('HSH', 'HS'): 'HSS', ('HSH', 'SS'): 'SSSHS', ('HSH', 'HSH'): 'HSSH', ('HSH', 'SSH'): 'SSSHSH', ('HSH', 'SHS'): 'I', ('HSH', 'HSS'): 'SHSH', ('HSH', 'SSS'): 'HSSHSH', ('HSH', 'SHSH'): 'H', ('HSH', 'HSSH'): 'SHS', ('HSH', 'SSSH'): 'HSSHS', ('HSH', 'SSHS'): 'SSH', ('HSH', 'SHSS'): 'S', ('HSH', 'SSHSH'): 'SS', ('HSH', 'SHSSH'): 'SH', ('HSH', 'HSSHS'): 'SHSS', ('HSH', 'SSSHS'): 'SSHSSH', ('HSH', 'SSHSS'): 'SSHS', ('HSH', 'HSSHSH'): 'SHSSH', ('HSH', 'SSSHSH'): 'SSHSS', ('HSH', 'SSHSSH'): 'SSHSH',
    
    ('SSH', 'I'): 'SSH', ('SSH', 'H'): 'SS', ('SSH', 'S'): 'SSHS', ('SSH', 'SH'): 'SSHSH', ('SSH', 'HS'): 'SSS', ('SSH', 'SS'): 'SSHSS', ('SSH', 'HSH'): 'SSSH', ('SSH', 'SSH'): 'SSHSSH', ('SSH', 'SHS'): 'SH', ('SSH', 'HSS'): 'I', ('SSH', 'SSS'): 'SSSHSH', ('SSH', 'SHSH'): 'S', ('SSH', 'HSSH'): 'H', ('SSH', 'SSSH'): 'SSSHS', ('SSH', 'SSHS'): 'SHSSH', ('SSH', 'SHSS'): 'SHS', ('SSH', 'SSHSH'): 'SHSS', ('SSH', 'SHSSH'): 'SHSH', ('SSH', 'HSSHS'): 'HS', ('SSH', 'SSSHS'): 'HSSHSH', ('SSH', 'SSHSS'): 'HSSH', ('SSH', 'HSSHSH'): 'HSH', ('SSH', 'SSSHSH'): 'HSSHS', ('SSH', 'SSHSSH'): 'HSS',
    
    ('SHS', 'I'): 'SHS', ('SHS', 'H'): 'SHSH', ('SHS', 'S'): 'SHSS', ('SHS', 'SH'): 'SHSSH', ('SHS', 'HS'): 'H', ('SHS', 'SS'): 'SSHSH', ('SHS', 'HSH'): 'I', ('SHS', 'SSH'): 'SSHS', ('SHS', 'SHS'): 'HSSH', ('SHS', 'HSS'): 'HS', ('SHS', 'SSS'): 'SH', ('SHS', 'SHSH'): 'HSS', ('SHS', 'HSSH'): 'HSH', ('SHS', 'SSSH'): 'S', ('SHS', 'SSHS'): 'SSHSS', ('SHS', 'SHSS'): 'HSSHS', ('SHS', 'SSHSH'): 'SSHSSH', ('SHS', 'SHSSH'): 'HSSHSH', ('SHS', 'HSSHS'): 'SSSH', ('SHS', 'SSSHS'): 'SS', ('SHS', 'SSHSS'): 'SSSHSH', ('SHS', 'HSSHSH'): 'SSS', ('SHS', 'SSSHSH'): 'SSH', ('SHS', 'SSHSSH'): 'SSSHS',
    
    ('HSS', 'I'): 'HSS', ('HSS', 'H'): 'HSSH', ('HSS', 'S'): 'SHSH', ('HSS', 'SH'): 'SHS', ('HSS', 'HS'): 'HSSHS', ('HSS', 'SS'): 'H', ('HSS', 'HSH'): 'HSSHSH', ('HSS', 'SSH'): 'I', ('HSS', 'SHS'): 'SHSS', ('HSS', 'HSS'): 'SSHSSH', ('HSS', 'SSS'): 'HS', ('HSS', 'SHSH'): 'SHSSH', ('HSS', 'HSSH'): 'SSHSS', ('HSS', 'SSSH'): 'HSH', ('HSS', 'SSHS'): 'S', ('HSS', 'SHSS'): 'SSHSH', ('HSS', 'SSHSH'): 'SH', ('HSS', 'SHSSH'): 'SSHS', ('HSS', 'HSSHS'): 'SSSHSH', ('HSS', 'SSSHS'): 'SSSH', ('HSS', 'SSHSS'): 'SS', ('HSS', 'HSSHSH'): 'SSSHS', ('HSS', 'SSSHSH'): 'SSS', ('HSS', 'SSHSSH'): 'SSH',
    
    ('SSS', 'I'): 'SSS', ('SSS', 'H'): 'SSSH', ('SSS', 'S'): 'I', ('SSS', 'SH'): 'H', ('SSS', 'HS'): 'SSSHS', ('SSS', 'SS'): 'S', ('SSS', 'HSH'): 'SSSHSH', ('SSS', 'SSH'): 'SH', ('SSS', 'SHS'): 'HS', ('SSS', 'HSS'): 'HSSHSH', ('SSS', 'SSS'): 'SS', ('SSS', 'SHSH'): 'HSH', ('SSS', 'HSSH'): 'HSSHS', ('SSS', 'SSSH'): 'SSH', ('SSS', 'SSHS'): 'SHS', ('SSS', 'SHSS'): 'HSS', ('SSS', 'SSHSH'): 'SHSH', ('SSS', 'SHSSH'): 'HSSH', ('SSS', 'HSSHS'): 'SSHSSH', ('SSS', 'SSSHS'): 'SSHS', ('SSS', 'SSHSS'): 'SHSS', ('SSS', 'HSSHSH'): 'SSHSS', ('SSS', 'SSSHSH'): 'SSHSH', ('SSS', 'SSHSSH'): 'SHSSH',
    
    ('SHSH', 'I'): 'SHSH', ('SHSH', 'H'): 'SHS', ('SHSH', 'S'): 'H', ('SHSH', 'SH'): 'I', ('SHSH', 'HS'): 'SHSS', ('SHSH', 'SS'): 'HS', ('SHSH', 'HSH'): 'SHSSH', ('SHSH', 'SSH'): 'HSH', ('SHSH', 'SHS'): 'S', ('SHSH', 'HSS'): 'SSHSH', ('SHSH', 'SSS'): 'HSS', ('SHSH', 'SHSH'): 'SH', ('SHSH', 'HSSH'): 'SSHS', ('SHSH', 'SSSH'): 'HSSH', ('SHSH', 'SSHS'): 'SSSH', ('SHSH', 'SHSS'): 'SS', ('SHSH', 'SSHSH'): 'SSS', ('SHSH', 'SHSSH'): 'SSH', ('SHSH', 'HSSHS'): 'SSHSS', ('SHSH', 'SSSHS'): 'HSSHS', ('SHSH', 'SSHSS'): 'SSSHS', ('SHSH', 'HSSHSH'): 'SSHSSH', ('SHSH', 'SSSHSH'): 'HSSHSH', ('SHSH', 'SSHSSH'): 'SSSHSH',
    
    ('HSSH', 'I'): 'HSSH', ('HSSH', 'H'): 'HSS', ('HSSH', 'S'): 'HSSHS', ('HSSH', 'SH'): 'HSSHSH', ('HSSH', 'HS'): 'SHSH', ('HSSH', 'SS'): 'SSHSSH', ('HSSH', 'HSH'): 'SHS', ('HSSH', 'SSH'): 'SSHSS', ('HSSH', 'SHS'): 'HSH', ('HSSH', 'HSS'): 'H', ('HSSH', 'SSS'): 'SHSSH', ('HSSH', 'SHSH'): 'HS', ('HSSH', 'HSSH'): 'I', ('HSSH', 'SSSH'): 'SHSS', ('HSSH', 'SSHS'): 'SSSHSH', ('HSSH', 'SHSS'): 'SSSH', ('HSSH', 'SSHSH'): 'SSSHS', ('HSSH', 'SHSSH'): 'SSS', ('HSSH', 'HSSHS'): 'S', ('HSSH', 'SSSHS'): 'SSHSH', ('HSSH', 'SSHSS'): 'SSH', ('HSSH', 'HSSHSH'): 'SH', ('HSSH', 'SSSHSH'): 'SSHS', ('HSSH', 'SSHSSH'): 'SS',
    
    ('SSSH', 'I'): 'SSSH', ('SSSH', 'H'): 'SSS', ('SSSH', 'S'): 'SSSHS', ('SSSH', 'SH'): 'SSSHSH', ('SSSH', 'HS'): 'I', ('SSSH', 'SS'): 'HSSHSH', ('SSSH', 'HSH'): 'H', ('SSSH', 'SSH'): 'HSSHS', ('SSSH', 'SHS'): 'SSH', ('SSSH', 'HSS'): 'S', ('SSSH', 'SSS'): 'HSH', ('SSSH', 'SHSH'): 'SS', ('SSSH', 'HSSH'): 'SH', ('SSSH', 'SSSH'): 'HS', ('SSSH', 'SSHS'): 'SSHSSH', ('SSSH', 'SHSS'): 'SSHS', ('SSSH', 'SSHSH'): 'SSHSS', ('SSSH', 'SHSSH'): 'SSHSH', ('SSSH', 'HSSHS'): 'SHS', ('SSSH', 'SSSHS'): 'HSS', ('SSSH', 'SSHSS'): 'SHSSH', ('SSSH', 'HSSHSH'): 'SHSH', ('SSSH', 'SSSHSH'): 'HSSH', ('SSSH', 'SSHSSH'): 'SHSS',
    
    ('SSHS', 'I'): 'SSHS', ('SSHS', 'H'): 'SSHSH', ('SSHS', 'S'): 'SSHSS', ('SSHS', 'SH'): 'SSHSSH', ('SSHS', 'HS'): 'SH', ('SSHS', 'SS'): 'SSSHSH', ('SSHS', 'HSH'): 'S', ('SSHS', 'SSH'): 'SSSHS', ('SSHS', 'SHS'): 'SHSSH', ('SSHS', 'HSS'): 'SHS', ('SSHS', 'SSS'): 'SSH', ('SSHS', 'SHSH'): 'SHSS', ('SSHS', 'HSSH'): 'SHSH', ('SSHS', 'SSSH'): 'SS', ('SSHS', 'SSHS'): 'HSSHSH', ('SSHS', 'SHSS'): 'HSSH', ('SSHS', 'SSHSH'): 'HSSHS', ('SSHS', 'SHSSH'): 'HSS', ('SSHS', 'HSSHS'): 'H', ('SSHS', 'SSSHS'): 'SSS', ('SSHS', 'SSHSS'): 'HSH', ('SSHS', 'HSSHSH'): 'I', ('SSHS', 'SSSHSH'): 'SSSH', ('SSHS', 'SSHSSH'): 'HS',
    
    ('SHSS', 'I'): 'SHSS', ('SHSS', 'H'): 'SHSSH', ('SHSS', 'S'): 'SSHSH', ('SHSS', 'SH'): 'SSHS', ('SHSS', 'HS'): 'HSSH', ('SHSS', 'SS'): 'SH', ('SHSS', 'HSH'): 'HSS', ('SHSS', 'SSH'): 'S', ('SHSS', 'SHS'): 'SSHSS', ('SHSS', 'HSS'): 'HSSHS', ('SHSS', 'SSS'): 'SHS', ('SHSS', 'SHSH'): 'SSHSSH', ('SHSS', 'HSSH'): 'HSSHSH', ('SHSS', 'SSSH'): 'SHSH', ('SHSS', 'SSHS'): 'SS', ('SHSS', 'SHSS'): 'SSSHSH', ('SHSS', 'SSHSH'): 'SSH', ('SHSS', 'SHSSH'): 'SSSHS', ('SHSS', 'HSSHS'): 'HSH', ('SHSS', 'SSSHS'): 'H', ('SHSS', 'SSHSS'): 'SSS', ('SHSS', 'HSSHSH'): 'HS', ('SHSS', 'SSSHSH'): 'I', ('SHSS', 'SSHSSH'): 'SSSH',
    
    ('SSHSH', 'I'): 'SSHSH', ('SSHSH', 'H'): 'SSHS', ('SSHSH', 'S'): 'SH', ('SSHSH', 'SH'): 'S', ('SSHSH', 'HS'): 'SSHSS', ('SSHSH', 'SS'): 'SHS', ('SSHSH', 'HSH'): 'SSHSSH', ('SSHSH', 'SSH'): 'SHSH', ('SSHSH', 'SHS'): 'SS', ('SSHSH', 'HSS'): 'SSSHSH', ('SSHSH', 'SSS'): 'SHSS', ('SSHSH', 'SHSH'): 'SSH', ('SSHSH', 'HSSH'): 'SSSHS', ('SSHSH', 'SSSH'): 'SHSSH', ('SSHSH', 'SSHS'): 'H', ('SSHSH', 'SHSS'): 'SSS', ('SSHSH', 'SSHSH'): 'I', ('SSHSH', 'SHSSH'): 'SSSH', ('SSHSH', 'HSSHS'): 'HSSHSH', ('SSHSH', 'SSSHS'): 'HSSH', ('SSHSH', 'SSHSS'): 'HS', ('SSHSH', 'HSSHSH'): 'HSSHS', ('SSHSH', 'SSSHSH'): 'HSS', ('SSHSH', 'SSHSSH'): 'HSH',
    
    ('SHSSH', 'I'): 'SHSSH', ('SHSSH', 'H'): 'SHSS', ('SHSSH', 'S'): 'HSSH', ('SHSSH', 'SH'): 'HSS', ('SHSSH', 'HS'): 'SSHSH', ('SHSSH', 'SS'): 'HSSHS', ('SHSSH', 'HSH'): 'SSHS', ('SHSSH', 'SSH'): 'HSSHSH', ('SHSSH', 'SHS'): 'SHSH', ('SHSSH', 'HSS'): 'SH', ('SHSSH', 'SSS'): 'SSHSSH', ('SHSSH', 'SHSH'): 'SHS', ('SHSSH', 'HSSH'): 'S', ('SHSSH', 'SSSH'): 'SSHSS', ('SHSSH', 'SSHS'): 'HSH', ('SHSSH', 'SHSS'): 'H', ('SHSSH', 'SSHSH'): 'HS', ('SHSSH', 'SHSSH'): 'I', ('SHSSH', 'HSSHS'): 'SS', ('SHSSH', 'SSSHS'): 'SSSHSH', ('SHSSH', 'SSHSS'): 'SSSH', ('SHSSH', 'HSSHSH'): 'SSH', ('SHSSH', 'SSSHSH'): 'SSSHS', ('SHSSH', 'SSHSSH'): 'SSS',
    
    ('HSSHS', 'I'): 'HSSHS', ('HSSHS', 'H'): 'HSSHSH', ('HSSHS', 'S'): 'SSHSSH', ('HSSHS', 'SH'): 'SSHSS', ('HSSHS', 'HS'): 'HSH', ('HSSHS', 'SS'): 'SHSSH', ('HSSHS', 'HSH'): 'HS', ('HSSHS', 'SSH'): 'SHSS', ('HSSHS', 'SHS'): 'SSSHSH', ('HSSHS', 'HSS'): 'SSSH', ('HSSHS', 'SSS'): 'HSSH', ('HSSHS', 'SHSH'): 'SSSHS', ('HSSHS', 'HSSH'): 'SSS', ('HSSHS', 'SSSH'): 'HSS', ('HSSHS', 'SSHS'): 'SSHSH', ('HSSHS', 'SHSS'): 'SSH', ('HSSHS', 'SSHSH'): 'SSHS', ('HSSHS', 'SHSSH'): 'SS', ('HSSHS', 'HSSHS'): 'I', ('HSSHS', 'SSSHS'): 'SHSH', ('HSSHS', 'SSHSS'): 'SH', ('HSSHS', 'HSSHSH'): 'H', ('HSSHS', 'SSSHSH'): 'SHS', ('HSSHS', 'SSHSSH'): 'S',
    
    ('SSSHS', 'I'): 'SSSHS', ('SSSHS', 'H'): 'SSSHSH', ('SSSHS', 'S'): 'HSSHSH', ('SSSHS', 'SH'): 'HSSHS', ('SSSHS', 'HS'): 'SSH', ('SSSHS', 'SS'): 'HSH', ('SSSHS', 'HSH'): 'SS', ('SSSHS', 'SSH'): 'HS', ('SSSHS', 'SHS'): 'SSHSSH', ('SSSHS', 'HSS'): 'SSHS', ('SSSHS', 'SSS'): 'SSSH', ('SSSHS', 'SHSH'): 'SSHSS', ('SSSHS', 'HSSH'): 'SSHSH', ('SSSHS', 'SSSH'): 'SSS', ('SSSHS', 'SSHS'): 'HSS', ('SSSHS', 'SHSS'): 'SHSSH', ('SSSHS', 'SSHSH'): 'HSSH', ('SSSHS', 'SHSSH'): 'SHSS', ('SSSHS', 'HSSHS'): 'SH', ('SSSHS', 'SSSHS'): 'I', ('SSSHS', 'SSHSS'): 'SHSH', ('SSSHS', 'HSSHSH'): 'S', ('SSSHS', 'SSSHSH'): 'H', ('SSSHS', 'SSHSSH'): 'SHS',
    
    ('SSHSS', 'I'): 'SSHSS', ('SSHSS', 'H'): 'SSHSSH', ('SSHSS', 'S'): 'SSSHSH', ('SSHSS', 'SH'): 'SSSHS', ('SSHSS', 'HS'): 'SHSSH', ('SSHSS', 'SS'): 'SSH', ('SSHSS', 'HSH'): 'SHSS', ('SSHSS', 'SSH'): 'SS', ('SSHSS', 'SHS'): 'HSSHSH', ('SSHSS', 'HSS'): 'HSSH', ('SSHSS', 'SSS'): 'SSHS', ('SSHSS', 'SHSH'): 'HSSHS', ('SSHSS', 'HSSH'): 'HSS', ('SSHSS', 'SSSH'): 'SSHSH', ('SSHSS', 'SSHS'): 'SSS', ('SSHSS', 'SHSS'): 'HSH', ('SSHSS', 'SSHSH'): 'SSSH', ('SSHSS', 'SHSSH'): 'HS', ('SSHSS', 'HSSHS'): 'SHSH', ('SSHSS', 'SSSHS'): 'SH', ('SSHSS', 'SSHSS'): 'I', ('SSHSS', 'HSSHSH'): 'SHS', ('SSHSS', 'SSSHSH'): 'S', ('SSHSS', 'SSHSSH'): 'H',
    
    ('HSSHSH', 'I'): 'HSSHSH', ('HSSHSH', 'H'): 'HSSHS', ('HSSHSH', 'S'): 'HSH', ('HSSHSH', 'SH'): 'HS', ('HSSHSH', 'HS'): 'SSHSSH', ('HSSHSH', 'SS'): 'SSSH', ('HSSHSH', 'HSH'): 'SSHSS', ('HSSHSH', 'SSH'): 'SSS', ('HSSHSH', 'SHS'): 'HSS', ('HSSHSH', 'HSS'): 'SHSSH', ('HSSHSH', 'SSS'): 'SSSHS', ('HSSHSH', 'SHSH'): 'HSSH', ('HSSHSH', 'HSSH'): 'SHSS', ('HSSHSH', 'SSSH'): 'SSSHSH', ('HSSHSH', 'SSHS'): 'I', ('HSSHSH', 'SHSS'): 'SHSH', ('HSSHSH', 'SSHSH'): 'H', ('HSSHSH', 'SHSSH'): 'SHS', ('HSSHSH', 'HSSHS'): 'SSHSH', ('HSSHSH', 'SSSHS'): 'SSH', ('HSSHSH', 'SSHSS'): 'S', ('HSSHSH', 'HSSHSH'): 'SSHS', ('HSSHSH', 'SSSHSH'): 'SS', ('HSSHSH', 'SSHSSH'): 'SH',
    
    ('SSSHSH', 'I'): 'SSSHSH', ('SSSHSH', 'H'): 'SSSHS', ('SSSHSH', 'S'): 'SSH', ('SSSHSH', 'SH'): 'SS', ('SSSHSH', 'HS'): 'HSSHSH', ('SSSHSH', 'SS'): 'SSHS', ('SSSHSH', 'HSH'): 'HSSHS', ('SSSHSH', 'SSH'): 'SSHSH', ('SSSHSH', 'SHS'): 'SSS', ('SSSHSH', 'HSS'): 'HSH', ('SSSHSH', 'SSS'): 'SSHSS', ('SSSHSH', 'SHSH'): 'SSSH', ('SSSHSH', 'HSSH'): 'HS', ('SSSHSH', 'SSSH'): 'SSHSSH', ('SSSHSH', 'SSHS'): 'SH', ('SSSHSH', 'SHSS'): 'I', ('SSSHSH', 'SSHSH'): 'S', ('SSSHSH', 'SHSSH'): 'H', ('SSSHSH', 'HSSHS'): 'HSS', ('SSSHSH', 'SSSHS'): 'SHSSH', ('SSSHSH', 'SSHSS'): 'SHS', ('SSSHSH', 'HSSHSH'): 'HSSH', ('SSSHSH', 'SSSHSH'): 'SHSS', ('SSSHSH', 'SSHSSH'): 'SHSH',
    
    ('SSHSSH', 'I'): 'SSHSSH', ('SSHSSH', 'H'): 'SSHSS', ('SSHSSH', 'S'): 'SHSSH', ('SSHSSH', 'SH'): 'SHSS', ('SSHSSH', 'HS'): 'SSSHSH', ('SSHSSH', 'SS'): 'HSSH', ('SSHSSH', 'HSH'): 'SSSHS', ('SSHSSH', 'SSH'): 'HSS', ('SSHSSH', 'SHS'): 'SSHSH', ('SSHSSH', 'HSS'): 'SSH', ('SSHSSH', 'SSS'): 'HSSHS', ('SSHSSH', 'SHSH'): 'SSHS', ('SSHSSH', 'HSSH'): 'SS', ('SSHSSH', 'SSSH'): 'HSSHSH', ('SSHSSH', 'SSHS'): 'SHSH', ('SSHSSH', 'SHSS'): 'SH', ('SSHSSH', 'SSHSH'): 'SHS', ('SSHSSH', 'SHSSH'): 'S', ('SSHSSH', 'HSSHS'): 'SSS', ('SSHSSH', 'SSSHS'): 'HSH', ('SSHSSH', 'SSHSS'): 'H', ('SSHSSH', 'HSSHSH'): 'SSSH', ('SSHSSH', 'SSSHSH'): 'HS', ('SSHSSH', 'SSHSSH'): 'I'
}